# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration

require 'rack/test'
require 'pry-debugger'
require 'database_cleaner'
require 'factory_girl'

require_relative '../app.rb'

ENV["RACK_ENV"] = "test"

# Rspec helpers
Dir[File.join Sinatra::Application.root, 'spec/helper/*.rb'].each {|f| require f}

# Factories
Dir[File.join Sinatra::Application.root, 'spec/factories/*.rb'].each {|f| require f}

module RSpecMixin
  include Rack::Test::Methods
  def app() Sinatra::Application end
end

RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'

  config.expect_with :rspec do |c|
    # Disable the 'should' syntax
    c.syntax = :expect
  end

  # Include Helpers Module app
  config.include RSpecMixin
  config.include RSpecHelper

  # Database cleaner
  config.before :suite do
    DatabaseCleaner.strategy = :truncation
    DatabaseCleaner.clean_with :truncation
  end

  config.before :each do
    DatabaseCleaner.start
  end

  config.after :each do
    DatabaseCleaner.clean
  end
end
